# Generated by Django 6.0 on 2025-12-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Comment Category')),
                ('category', models.CharField(choices=[('A', 'Appreciation'), ('I', 'Impression'), ('G', 'Growth'), ('S', 'Suggestion'), ('D', 'Discussion')], default='A', max_length=1)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.interest')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
