# Generated by Django 6.0 on 2025-12-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_comment_comment_interest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default=1, max_length=20000),
            preserve_default=False,
        ),
    ]
